coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
